# Generated by Django 4.2.6 on 2023-10-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0004_alter_quote_quote_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=1500),
        ),
    ]
