# Generated by Django 4.2.6 on 2023-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorsapp', '0004_alter_author_goodreads_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=45),
        ),
    ]
